version: '3.8'

services:
  web:
    build:
      context: .
    image: dplouffe/oel-server-web:latest
    container_name: oel-server-web
    command: ["web"]
    env_file: .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build:
      context: .
    image: dplouffe/oel-server-celery:latest
    container_name: oel-server-celery
    command: ["celery"]
    env_file: .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
      - web

  celery-beat:
    build:
      context: .
    image: dplouffe/oel-server-beat:latest
    container_name: oel-server-beat
    command: ["beat"]
    env_file: .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
      - web

  redis:
    image: redis:7-alpine
    container_name: oel-server-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
