# Generated by Django 3.1.1 on 2020-09-19 23:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('endpoint', models.CharField(max_length=255)),
                ('endpoint_username', models.CharField(blank=True, max_length=255, null=True)),
                ('endpoint_password', models.CharField(blank=True, max_length=255, null=True)),
                ('interval', models.IntegerField()),
                ('status_code', models.IntegerField()),
                ('content_type', models.CharField(choices=[('Text', 'text/plain'), ('JSON', 'application/json')], max_length=20)),
                ('expected_string', models.CharField(blank=True, max_length=1000, null=True)),
                ('expeted_value', models.CharField(blank=True, max_length=1000, null=True)),
                ('callback_url', models.CharField(max_length=255)),
                ('callback_userame', models.CharField(blank=True, max_length=255, null=True)),
                ('callback_password', models.CharField(blank=True, max_length=255, null=True)),
                ('callback_email', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.org')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_date', models.DateTimeField()),
                ('result_type', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('success', models.IntegerField()),
                ('failure', models.IntegerField()),
                ('total_time', models.IntegerField()),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ping')),
            ],
        ),
        migrations.CreateModel(
            name='PingHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('header_type', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ping')),
            ],
        ),
        migrations.CreateModel(
            name='OrgUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('email_verified_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.org')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.CharField(blank=True, max_length=10000, null=True)),
                ('chpingeck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ping')),
            ],
        ),
    ]
