# Generated by Django 3.1.1 on 2020-09-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200919_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ping',
            name='callback_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
