# Generated by Django 3.1.1 on 2020-09-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200919_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
