# Generated by Django 3.1.1 on 2020-09-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ping_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ping',
            old_name='expeted_value',
            new_name='expected_value',
        ),
        migrations.AlterField(
            model_name='ping',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'Text'), ('application/json', 'JSON')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pingheader',
            name='header_type',
            field=models.CharField(choices=[('endpoint', 'Endpoint'), ('callback', 'Callback')], max_length=20),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_type',
            field=models.CharField(choices=[('hour', 'Hour'), ('day', 'Day')], max_length=20),
        ),
    ]
