# Generated by Django 3.1.1 on 2020-09-20 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200920_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='failure',
            old_name='chpingeck',
            new_name='ping',
        ),
    ]
