# Generated by Django 3.1.1 on 2020-09-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200920_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='notified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
