# Generated by Django 3.1.1 on 2020-09-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ping_notified_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='reason',
            field=models.CharField(blank=True, choices=[('invalid_value', 'Invalid Value'), ('key_error', 'Key Error'), ('value_error', 'Value Error'), ('status_code', 'Status Code'), ('connection_error', 'Connection Error'), ('timeout_error', 'Timeout Error'), ('http_error', 'HTTP Error')], max_length=20, null=True),
        ),
    ]
