# Generated by Django 3.1.1 on 2020-09-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200920_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='incident_interval',
            field=models.IntegerField(default=1),
        ),
    ]
