# Generated by Django 3.1.1 on 2020-09-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ping_incident_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ping',
            name='callback_num_calls',
        ),
    ]
