# Generated by Django 3.1.1 on 2020-10-18 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_ping_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='failure',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
