# Generated by Django 3.1.1 on 2020-10-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_failure_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='orguser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orguser',
            name='phone_number_verified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
