# Generated by Django 3.1.1 on 2020-10-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
        ('api', '0015_auto_20201022_1035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ping',
            new_name='PingPong',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='ping',
            new_name='pingpong',
        ),
    ]
