# Generated by Django 3.1.1 on 2020-10-26 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201026_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pingheader',
            old_name='ping',
            new_name='pingpong',
        ),
    ]
