# Generated by Django 3.1.1 on 2020-10-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201026_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingpong',
            name='pingpong_type',
            field=models.CharField(choices=[('ping', 'Ping'), ('pong', 'Pong')], default='ping', max_length=20),
        ),
        migrations.AddField(
            model_name='pingpong',
            name='pong_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pingpong',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'Text'), ('application/json', 'JSON')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pingpong',
            name='endpoint',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pingpong',
            name='expected_string',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pingpong',
            name='interval',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pingpong',
            name='status_code',
            field=models.IntegerField(null=True),
        ),
    ]
