# Generated by Django 3.1.1 on 2020-10-27 13:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20201026_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='PongData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('data', models.JSONField()),
                ('pong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pingpong')),
            ],
        ),
    ]
