# Generated by Django 3.1.1 on 2020-10-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_pongdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='failure',
            old_name='ping',
            new_name='pingpong',
        ),
    ]
