# Generated by Django 3.1.1 on 2020-10-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20201028_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='orguser',
            name='notificationtype',
            field=models.CharField(choices=[('Email', 'email'), ('Text', 'text')], default='email', max_length=20),
        ),
    ]
