# Generated by Django 3.1.1 on 2020-10-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_orguser_notificationtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orguser',
            name='notificationtype',
        ),
        migrations.AddField(
            model_name='orguser',
            name='notification_type',
            field=models.CharField(choices=[('email', 'Email'), ('text', 'Text')], default='email', max_length=20),
        ),
    ]
