# Generated by Django 3.1.1 on 2020-10-28 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20201028_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pingpong',
            name='callback_email',
        ),
        migrations.RemoveField(
            model_name='pingpong',
            name='pingpong_type',
        ),
        migrations.RemoveField(
            model_name='pingpong',
            name='pong_key',
        ),
    ]
