# Generated by Django 3.1.1 on 2020-10-28 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
        ('api', '0023_auto_20201028_2350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PingPong',
            new_name='Ping',
        ),
        migrations.RenameField(
            model_name='failure',
            old_name='pingpong',
            new_name='ping',
        ),
        migrations.RenameField(
            model_name='pingheader',
            old_name='pingpong',
            new_name='ping',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='pingpong',
            new_name='ping',
        ),
    ]
