# Generated by Django 3.1.1 on 2020-10-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20201028_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='notification_type',
            field=models.CharField(choices=[('team', 'Team'), ('callback', 'Callback')], default='team', max_length=20),
            preserve_default=False,
        ),
    ]
