# Generated by Django 3.1.1 on 2020-10-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_ping_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orguser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='admin', max_length=20),
        ),
    ]
