# Generated by Django 3.1.1 on 2020-10-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_orguser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='orguser',
            name='is_oncall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orguser',
            name='oncall_order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
