# Generated by Django 3.1.1 on 2020-11-01 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_orguser_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orguser',
            name='week',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('org_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orguser')),
            ],
        ),
    ]
