# Generated by Django 3.1.1 on 2020-11-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_schedule_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orguser',
            name='week',
        ),
        migrations.AddField(
            model_name='org',
            name='week',
            field=models.IntegerField(default=1),
        ),
    ]
