# Generated by Django 3.1.1 on 2020-11-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20201101_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
