# Generated by Django 3.1.3 on 2020-11-26 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20201102_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='doc_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='NotificationBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(blank=True, choices=[('recovery', 'Recovery'), ('failure', 'Failure'), ('going-oncall', 'Going OnCall'), ('invite', 'Invitation'), ('confirmation', 'Confirmation')], max_length=20, null=True)),
                ('content', models.CharField(blank=True, max_length=10000, null=True)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.org')),
            ],
        ),
    ]
