# Generated by Django 3.1.3 on 2020-11-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20201126_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationbody',
            name='delivery',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('text', 'Text')], max_length=20, null=True),
        ),
    ]
