# Generated by Django 3.1.3 on 2020-12-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_notificationbody_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='direction',
            field=models.CharField(default='pull', max_length=10),
        ),
    ]
