# Generated by Django 3.1.3 on 2020-12-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_ping_api_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ping',
            old_name='api_key',
            new_name='push_key',
        ),
    ]
