# Generated by Django 3.1.3 on 2020-12-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
        ('api', '0039_auto_20201209_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ping',
            name='content_type',
            field=models.CharField(blank=True, choices=[('text/plain', 'Text'), ('application/json', 'JSON')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ping',
            name='direction',
            field=models.CharField(choices=[('push', 'Push'), ('pull', 'Pull')], default='pull', max_length=10),
        ),
        migrations.AlterField(
            model_name='ping',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ping',
            name='interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ping',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ping',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
