# Generated by Django 3.1.3 on 2020-12-09 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20201209_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='failure',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acknowledged_by', to='api.orguser'),
        ),
        migrations.AddField(
            model_name='failure',
            name='acknowledged_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='failure',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_by', to='api.orguser'),
        ),
        migrations.AddField(
            model_name='failure',
            name='fixed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='failure',
            name='ignored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ignored_by', to='api.orguser'),
        ),
        migrations.AddField(
            model_name='failure',
            name='ingored_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
