# Generated by Django 3.1.3 on 2020-12-09 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20201209_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='failure',
            old_name='ingored_on',
            new_name='ignored_on',
        ),
    ]
