# Generated by Django 3.1.5 on 2021-01-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_vitalinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ping',
            name='cron',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ping',
            name='heartbeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ping',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ping',
            name='period',
            field=models.CharField(choices=[('days', 'Days'), ('hours', 'Hours'), ('minutes', 'Minutes'), ('seconds', 'Seconds'), ('microseconds', 'Microseconds')], default='minutes', max_length=24),
        ),
    ]
