# Generated by Django 3.1.5 on 2021-01-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_vitalinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='heartbeat',
            field=models.BooleanField(default=False),
        ),
    ]
