# Generated by Django 3.1.3 on 2021-01-07 19:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_vitalinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('team', 'Team'), ('callback', 'Callback')], max_length=20)),
                ('incident_interval', models.IntegerField(default=1)),
                ('doc_link', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('failure_count', models.IntegerField(default=0)),
                ('callback_url', models.CharField(blank=True, max_length=255, null=True)),
                ('callback_userame', models.CharField(blank=True, max_length=255, null=True)),
                ('callback_password', models.CharField(blank=True, max_length=255, null=True)),
                ('notified_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='ping',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.alert'),
        ),
    ]
