# Generated by Django 3.1.4 on 2021-01-05 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_vitalinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('onerrorlog', 'OnErrorLog')], max_length=50)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('startup', 'Startup'), ('enterprise', 'Enterprise')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=50)),
                ('paypal_product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paypal_plan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paypal_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.org')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('org', 'product', 'plan'), name='u_subscription'),
        ),
    ]
