# Generated by Django 3.1.5 on 2021-01-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_ping_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='period',
            field=models.CharField(choices=[('days', 'Days'), ('hours', 'Hours'), ('minutes', 'Minutes'), ('seconds', 'Seconds'), ('microseconds', 'Microseconds')], default='minutes', max_length=24),
        ),
    ]
