# Generated by Django 3.1.3 on 2021-01-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20210107_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='callback_userame',
            new_name='callback_username',
        ),
    ]
