# Generated by Django 3.1.4 on 2021-01-07 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20210105_1434'),
    ]

    operations = [
        migrations.RunSQL("TRUNCATE api_subscription;"),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('paypal_product_id', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('limits', models.JSONField(default={})),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='paypal_plan_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='paypal_product_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='limits',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='org',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.org'),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('paypal_plan_id', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('limits', models.JSONField(default={})),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='api.product')),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='api.plan'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='api.product'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(
                fields=('product', 'name'), name='u_plan'),
        ),
    ]
