# Generated by Django 3.1.5 on 2021-01-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_ping_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
