# Generated by Django 3.1.3 on 2021-01-07 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20210107_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('push_key', models.CharField(blank=True, max_length=255, null=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.alert')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.org')),
            ],
        ),
    ]
