# Generated by Django 3.1.3 on 2021-01-07 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20210107_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='pong',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='pong',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
