# Generated by Django 3.1.3 on 2021-01-08 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20210107_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='failure',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.alert'),
        ),
        migrations.AddField(
            model_name='result',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.alert'),
        ),
    ]
