# Generated by Django 3.1.3 on 2021-01-08 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20210108_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.org'),
        ),
    ]
