# Generated by Django 3.1.3 on 2021-01-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_metriccondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='metriccondition',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
