# Generated by Django 3.1.3 on 2021-01-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_metriccondition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='reason',
            field=models.CharField(blank=True, choices=[('invalid_value', 'Invalid Value'), ('key_error', 'Key Error'), ('value_error', 'Value Error'), ('status_code', 'Status Code'), ('connection_error', 'Connection Error'), ('timeout_error', 'Timeout Error'), ('http_error', 'HTTP Error'), ('receive_alert', 'Receive Alert'), ('Metric triggered', 'Metric Triggered')], max_length=20, null=True),
        ),
    ]
