# Generated by Django 3.1.3 on 2021-01-17 14:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20210110_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='PongTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('not_triggered', 'Heartbeat not triggered'), ('complete_not_triggered', 'Complete not triggered'), ('any_trigger', 'Heartbeat has been triggered'), ('runs_less_than', 'Runs less than'), ('runs_more_than', 'Runs more than')], max_length=50)),
                ('interval_value', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('pong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pong')),
            ],
        ),
    ]
