# Generated by Django 3.1.3 on 2021-01-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_pongtrigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='pong',
            name='last_complete_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pong',
            name='last_start_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pongtrigger',
            name='trigger_type',
            field=models.CharField(choices=[('complete_not_triggered_in', 'Complete not triggered'), ('start_not_triggered_in', 'Start not triggered'), ('heartbeat_triggered', 'Heartbeat has been triggered'), ('runs_less_than', 'Runs less than'), ('runs_more_than', 'Runs more than')], max_length=50),
        ),
    ]
