# Generated by Django 3.1.3 on 2021-01-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20210117_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='pong',
            name='cron_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pong',
            name='last_start_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
