# Generated by Django 3.1.3 on 2021-01-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20210118_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='pongtrigger',
            name='unit',
            field=models.CharField(blank=True, choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('days', 'Days')], max_length=255, null=True),
        ),
    ]
