# Generated by Django 3.1.3 on 2021-01-20 15:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_pongtrigger_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='reason',
            field=models.CharField(blank=True, choices=[('invalid_value', 'Invalid Value'), ('key_error', 'Key Error'), ('value_error', 'Value Error'), ('status_code', 'Status Code'), ('connection_error', 'Connection Error'), ('timeout_error', 'Timeout Error'), ('http_error', 'HTTP Error'), ('receive_alert', 'Receive Alert'), ('Metric triggered', 'Metric Triggered'), ('start_not_triggered', 'Heartbeat Start'), ('comp_not_triggered', 'Heartbeat Complete'), ('heartbeat_triggered', 'Heartbeat has been triggered'), ('runs_less_than', 'Runs less than'), ('runs_more_than', 'Runs more than')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ScheduleOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.org')),
                ('org_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orguser')),
            ],
        ),
    ]
