# Generated by Django 3.1.3 on 2021-01-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20210120_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ping',
            name='callback_password',
        ),
        migrations.RemoveField(
            model_name='ping',
            name='callback_url',
        ),
        migrations.RemoveField(
            model_name='ping',
            name='callback_userame',
        ),
        migrations.RemoveField(
            model_name='ping',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='ping',
            name='doc_link',
        ),
        migrations.RemoveField(
            model_name='ping',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='ping',
            name='endpoint_password',
        ),
        migrations.RemoveField(
            model_name='ping',
            name='endpoint_username',
        ),
        migrations.RemoveField(
            model_name='ping',
            name='failure_count',
        ),
        migrations.RemoveField(
            model_name='ping',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='ping',
            name='notified_on',
        ),
        migrations.RemoveField(
            model_name='ping',
            name='push_key',
        ),
    ]
