# Generated by Django 5.2.2 on 2025-07-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_alter_alert_created_on_alter_failure_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='metrics',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='tags',
        ),
        migrations.AddField(
            model_name='metric',
            name='metric_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='metric_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
